language: node_js
node_js:
  - "4.1"
before_install:
  - npm install -g coveralls
  - npm install -g gulp
  - npm install -g karma-cli
  - npm install -g tsd
install:
  - npm install
  - tsd install
before_script: gulp
script: npm run-script test
after_success:
  - coveralls
